orbs:
  slack: circleci/slack@3.4.2
version: 2.1
executors:
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small
jobs:
  build:
    docker: 
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache: 
          keys:
            - app-{{checksum "package.json"}}
            - app-
      - run:
          name: Install dependencies
          command: sudo yarn install 
      - save_cache:
          paths: 
            - node_modules
          key: app-{{checksum "package.json"}}
  notify-via-slack:
    executor: slack-executor
    steps:
      - slack/notify:
          message: "${CIRCLE_BRANCH} branch build is completed"
          webhook: $SLACK_WEBHOOK
      - slack/status:
          webhook: $SLACK_WEBHOOK
workflows:
  build_and_deploy:
    jobs:
      - build
      - notify-via-slack:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master



