version: 2.1

jobs:
  build:
    docker: 
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cash: 
          key:
            - app-{{checksum package.json}}
            - app-
      - run:
          name: Install yarn
          command: npm install -g yarn    
      - run:
          name: Install dependencies
          command: yarn install 
      - save_cash:
          paths: 
            - node_modules
          key: app-{{checksum package.json}}
workflows:
  butld_and_deploy:
    jobs:
      - build



